version: "3.9"

services:
  web:
    build: .
    restart: always
    ports:
        - "8000:80"
    depends_on:
        - db

  db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "UsmanProj991"
            ACCEPT_EULA: "Y"
        ports:
            - "1400:1433"